package template

const fileTpl = `// Code generated by github.com/j2gg0s/protoc-gen-dft. DO NOT EDIT.
// source: {{ .InputPath }}

package {{ pkg . }}

{{ range .AllMessages }}
	func (m {{ (msgTyp .).Pointer }}) SetDefault() {
		if m == nil { return }

		{{ range .NonOneOfFields }}
			{{ render (context .) }}
		{{ end }}

		{{ range .OneOfs }}
		switch m.{{ name . }}.(type) {
			{{ range .Fields }}
			case {{ oneof . }}:
				{{ render (context .) }}
			{{ end }}
		}
		{{ end }}
	}
{{ end }}
`

const noneTpl = `
	// {{ name .Field }} has not default.
`

const numTpl = `
	if {{ accessor . }} == 0 {
		m.{{ name .Field }} = {{ .Val }}
	}
`

const strTpl = `
	if len({{ accessor . }}) == 0 {
		m.{{ name .Field }} = "{{ .Val }}"
	}
`

const numsTpl = `
	if len({{ accessor . }}) == 0 {
		m.{{ name .Field }} = append(m.{{ name .Field }},
		{{- range .Val -}}
			{{ . }},
		{{- end -}}
		)
	}
`

const strsTpl = `
	if len({{ accessor . }}) == 0 {
		m.{{ name .Field }} = append(m.{{ name .Field }},
		{{- range .Val -}}
			"{{ . }}",
		{{- end -}}
		)
	}
`
