// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: dft/dft.proto

package dft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldDft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Dft:
	//	*FieldDft_Number
	//	*FieldDft_String_
	//	*FieldDft_Numbers
	//	*FieldDft_Strings
	//	*FieldDft_Json
	Dft isFieldDft_Dft `protobuf_oneof:"dft"`
}

func (x *FieldDft) Reset() {
	*x = FieldDft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dft_dft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldDft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDft) ProtoMessage() {}

func (x *FieldDft) ProtoReflect() protoreflect.Message {
	mi := &file_dft_dft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDft.ProtoReflect.Descriptor instead.
func (*FieldDft) Descriptor() ([]byte, []int) {
	return file_dft_dft_proto_rawDescGZIP(), []int{0}
}

func (m *FieldDft) GetDft() isFieldDft_Dft {
	if m != nil {
		return m.Dft
	}
	return nil
}

func (x *FieldDft) GetNumber() float64 {
	if x, ok := x.GetDft().(*FieldDft_Number); ok {
		return x.Number
	}
	return 0
}

func (x *FieldDft) GetString_() string {
	if x, ok := x.GetDft().(*FieldDft_String_); ok {
		return x.String_
	}
	return ""
}

func (x *FieldDft) GetNumbers() *NumberValues {
	if x, ok := x.GetDft().(*FieldDft_Numbers); ok {
		return x.Numbers
	}
	return nil
}

func (x *FieldDft) GetStrings() *StringValues {
	if x, ok := x.GetDft().(*FieldDft_Strings); ok {
		return x.Strings
	}
	return nil
}

func (x *FieldDft) GetJson() string {
	if x, ok := x.GetDft().(*FieldDft_Json); ok {
		return x.Json
	}
	return ""
}

type isFieldDft_Dft interface {
	isFieldDft_Dft()
}

type FieldDft_Number struct {
	Number float64 `protobuf:"fixed64,1,opt,name=number,proto3,oneof"`
}

type FieldDft_String_ struct {
	String_ string `protobuf:"bytes,2,opt,name=string,proto3,oneof"`
}

type FieldDft_Numbers struct {
	Numbers *NumberValues `protobuf:"bytes,3,opt,name=numbers,proto3,oneof"`
}

type FieldDft_Strings struct {
	Strings *StringValues `protobuf:"bytes,4,opt,name=strings,proto3,oneof"`
}

type FieldDft_Json struct {
	Json string `protobuf:"bytes,5,opt,name=json,proto3,oneof"`
}

func (*FieldDft_Number) isFieldDft_Dft() {}

func (*FieldDft_String_) isFieldDft_Dft() {}

func (*FieldDft_Numbers) isFieldDft_Dft() {}

func (*FieldDft_Strings) isFieldDft_Dft() {}

func (*FieldDft_Json) isFieldDft_Dft() {}

type NumberValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values string `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	// default ,
	Sep string `protobuf:"bytes,2,opt,name=sep,proto3" json:"sep,omitempty"`
	// default space
	Trim string `protobuf:"bytes,3,opt,name=trim,proto3" json:"trim,omitempty"`
}

func (x *NumberValues) Reset() {
	*x = NumberValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dft_dft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberValues) ProtoMessage() {}

func (x *NumberValues) ProtoReflect() protoreflect.Message {
	mi := &file_dft_dft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberValues.ProtoReflect.Descriptor instead.
func (*NumberValues) Descriptor() ([]byte, []int) {
	return file_dft_dft_proto_rawDescGZIP(), []int{1}
}

func (x *NumberValues) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

func (x *NumberValues) GetSep() string {
	if x != nil {
		return x.Sep
	}
	return ""
}

func (x *NumberValues) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

type StringValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values string `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	// default ,
	Sep string `protobuf:"bytes,2,opt,name=sep,proto3" json:"sep,omitempty"`
	// default space
	Trim string `protobuf:"bytes,3,opt,name=trim,proto3" json:"trim,omitempty"`
}

func (x *StringValues) Reset() {
	*x = StringValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dft_dft_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValues) ProtoMessage() {}

func (x *StringValues) ProtoReflect() protoreflect.Message {
	mi := &file_dft_dft_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValues.ProtoReflect.Descriptor instead.
func (*StringValues) Descriptor() ([]byte, []int) {
	return file_dft_dft_proto_rawDescGZIP(), []int{2}
}

func (x *StringValues) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

func (x *StringValues) GetSep() string {
	if x != nil {
		return x.Sep
	}
	return ""
}

func (x *StringValues) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

var file_dft_dft_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldDft)(nil),
		Field:         1081,
		Name:          "dft.dft",
		Tag:           "bytes,1081,opt,name=dft",
		Filename:      "dft/dft.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional dft.FieldDft dft = 1081;
	E_Dft = &file_dft_dft_proto_extTypes[0]
)

var File_dft_dft_proto protoreflect.FileDescriptor

var file_dft_dft_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x66, 0x74, 0x2f, 0x64, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x64, 0x66, 0x74, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x44, 0x66, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x66, 0x74, 0x2e, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x48, 0x00, 0x52, 0x07, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x66, 0x74, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x64,
	0x66, 0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x72, 0x69, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x72, 0x69, 0x6d,
	0x22, 0x4c, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x72,
	0x69, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x72, 0x69, 0x6d, 0x3a, 0x42,
	0x0a, 0x03, 0x64, 0x66, 0x74, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb9, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x66,
	0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x66, 0x74, 0x52, 0x03, 0x64, 0x66, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6a, 0x32, 0x67, 0x67, 0x30, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67,
	0x65, 0x6e, 0x2d, 0x64, 0x66, 0x74, 0x2f, 0x64, 0x66, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dft_dft_proto_rawDescOnce sync.Once
	file_dft_dft_proto_rawDescData = file_dft_dft_proto_rawDesc
)

func file_dft_dft_proto_rawDescGZIP() []byte {
	file_dft_dft_proto_rawDescOnce.Do(func() {
		file_dft_dft_proto_rawDescData = protoimpl.X.CompressGZIP(file_dft_dft_proto_rawDescData)
	})
	return file_dft_dft_proto_rawDescData
}

var file_dft_dft_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dft_dft_proto_goTypes = []interface{}{
	(*FieldDft)(nil),                  // 0: dft.FieldDft
	(*NumberValues)(nil),              // 1: dft.NumberValues
	(*StringValues)(nil),              // 2: dft.StringValues
	(*descriptorpb.FieldOptions)(nil), // 3: google.protobuf.FieldOptions
}
var file_dft_dft_proto_depIdxs = []int32{
	1, // 0: dft.FieldDft.numbers:type_name -> dft.NumberValues
	2, // 1: dft.FieldDft.strings:type_name -> dft.StringValues
	3, // 2: dft.dft:extendee -> google.protobuf.FieldOptions
	0, // 3: dft.dft:type_name -> dft.FieldDft
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dft_dft_proto_init() }
func file_dft_dft_proto_init() {
	if File_dft_dft_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dft_dft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldDft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dft_dft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dft_dft_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dft_dft_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*FieldDft_Number)(nil),
		(*FieldDft_String_)(nil),
		(*FieldDft_Numbers)(nil),
		(*FieldDft_Strings)(nil),
		(*FieldDft_Json)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dft_dft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_dft_dft_proto_goTypes,
		DependencyIndexes: file_dft_dft_proto_depIdxs,
		MessageInfos:      file_dft_dft_proto_msgTypes,
		ExtensionInfos:    file_dft_dft_proto_extTypes,
	}.Build()
	File_dft_dft_proto = out.File
	file_dft_dft_proto_rawDesc = nil
	file_dft_dft_proto_goTypes = nil
	file_dft_dft_proto_depIdxs = nil
}
