// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dft/dft.proto

package dft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldDft struct {
	// Types that are valid to be assigned to Dft:
	//	*FieldDft_Float
	//	*FieldDft_Double
	//	*FieldDft_Int32
	//	*FieldDft_Int64
	//	*FieldDft_Uint32
	//	*FieldDft_Uint64
	//	*FieldDft_Sint32
	//	*FieldDft_Sint64
	//	*FieldDft_Fixed32
	//	*FieldDft_Fixed64
	//	*FieldDft_Sfixed32
	//	*FieldDft_Sfixed64
	//	*FieldDft_Bool
	//	*FieldDft_String_
	//	*FieldDft_Bytes
	//	*FieldDft_Enum
	//	*FieldDft_Duration
	//	*FieldDft_Timestamp
	Dft                  isFieldDft_Dft `protobuf_oneof:"dft"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FieldDft) Reset()         { *m = FieldDft{} }
func (m *FieldDft) String() string { return proto.CompactTextString(m) }
func (*FieldDft) ProtoMessage()    {}
func (*FieldDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{0}
}

func (m *FieldDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDft.Unmarshal(m, b)
}
func (m *FieldDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDft.Marshal(b, m, deterministic)
}
func (m *FieldDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDft.Merge(m, src)
}
func (m *FieldDft) XXX_Size() int {
	return xxx_messageInfo_FieldDft.Size(m)
}
func (m *FieldDft) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDft.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDft proto.InternalMessageInfo

type isFieldDft_Dft interface {
	isFieldDft_Dft()
}

type FieldDft_Float struct {
	Float *FloatDft `protobuf:"bytes,1,opt,name=float,proto3,oneof"`
}

type FieldDft_Double struct {
	Double *DoubleDft `protobuf:"bytes,2,opt,name=double,proto3,oneof"`
}

type FieldDft_Int32 struct {
	Int32 *Int32Dft `protobuf:"bytes,3,opt,name=int32,proto3,oneof"`
}

type FieldDft_Int64 struct {
	Int64 *Int64Dft `protobuf:"bytes,4,opt,name=int64,proto3,oneof"`
}

type FieldDft_Uint32 struct {
	Uint32 *UInt32Dft `protobuf:"bytes,5,opt,name=uint32,proto3,oneof"`
}

type FieldDft_Uint64 struct {
	Uint64 *UInt64Dft `protobuf:"bytes,6,opt,name=uint64,proto3,oneof"`
}

type FieldDft_Sint32 struct {
	Sint32 *SInt32Dft `protobuf:"bytes,7,opt,name=sint32,proto3,oneof"`
}

type FieldDft_Sint64 struct {
	Sint64 *SInt64Dft `protobuf:"bytes,8,opt,name=sint64,proto3,oneof"`
}

type FieldDft_Fixed32 struct {
	Fixed32 *Fixed32Dft `protobuf:"bytes,9,opt,name=fixed32,proto3,oneof"`
}

type FieldDft_Fixed64 struct {
	Fixed64 *Fixed64Dft `protobuf:"bytes,10,opt,name=fixed64,proto3,oneof"`
}

type FieldDft_Sfixed32 struct {
	Sfixed32 *SFixed32Dft `protobuf:"bytes,11,opt,name=sfixed32,proto3,oneof"`
}

type FieldDft_Sfixed64 struct {
	Sfixed64 *SFixed64Dft `protobuf:"bytes,12,opt,name=sfixed64,proto3,oneof"`
}

type FieldDft_Bool struct {
	Bool *BoolDft `protobuf:"bytes,13,opt,name=bool,proto3,oneof"`
}

type FieldDft_String_ struct {
	String_ *StringDft `protobuf:"bytes,14,opt,name=string,proto3,oneof"`
}

type FieldDft_Bytes struct {
	Bytes *BytesDft `protobuf:"bytes,15,opt,name=bytes,proto3,oneof"`
}

type FieldDft_Enum struct {
	Enum *EnumDft `protobuf:"bytes,16,opt,name=enum,proto3,oneof"`
}

type FieldDft_Duration struct {
	Duration *DurationDft `protobuf:"bytes,21,opt,name=duration,proto3,oneof"`
}

type FieldDft_Timestamp struct {
	Timestamp *TimestampDft `protobuf:"bytes,22,opt,name=timestamp,proto3,oneof"`
}

func (*FieldDft_Float) isFieldDft_Dft() {}

func (*FieldDft_Double) isFieldDft_Dft() {}

func (*FieldDft_Int32) isFieldDft_Dft() {}

func (*FieldDft_Int64) isFieldDft_Dft() {}

func (*FieldDft_Uint32) isFieldDft_Dft() {}

func (*FieldDft_Uint64) isFieldDft_Dft() {}

func (*FieldDft_Sint32) isFieldDft_Dft() {}

func (*FieldDft_Sint64) isFieldDft_Dft() {}

func (*FieldDft_Fixed32) isFieldDft_Dft() {}

func (*FieldDft_Fixed64) isFieldDft_Dft() {}

func (*FieldDft_Sfixed32) isFieldDft_Dft() {}

func (*FieldDft_Sfixed64) isFieldDft_Dft() {}

func (*FieldDft_Bool) isFieldDft_Dft() {}

func (*FieldDft_String_) isFieldDft_Dft() {}

func (*FieldDft_Bytes) isFieldDft_Dft() {}

func (*FieldDft_Enum) isFieldDft_Dft() {}

func (*FieldDft_Duration) isFieldDft_Dft() {}

func (*FieldDft_Timestamp) isFieldDft_Dft() {}

func (m *FieldDft) GetDft() isFieldDft_Dft {
	if m != nil {
		return m.Dft
	}
	return nil
}

func (m *FieldDft) GetFloat() *FloatDft {
	if x, ok := m.GetDft().(*FieldDft_Float); ok {
		return x.Float
	}
	return nil
}

func (m *FieldDft) GetDouble() *DoubleDft {
	if x, ok := m.GetDft().(*FieldDft_Double); ok {
		return x.Double
	}
	return nil
}

func (m *FieldDft) GetInt32() *Int32Dft {
	if x, ok := m.GetDft().(*FieldDft_Int32); ok {
		return x.Int32
	}
	return nil
}

func (m *FieldDft) GetInt64() *Int64Dft {
	if x, ok := m.GetDft().(*FieldDft_Int64); ok {
		return x.Int64
	}
	return nil
}

func (m *FieldDft) GetUint32() *UInt32Dft {
	if x, ok := m.GetDft().(*FieldDft_Uint32); ok {
		return x.Uint32
	}
	return nil
}

func (m *FieldDft) GetUint64() *UInt64Dft {
	if x, ok := m.GetDft().(*FieldDft_Uint64); ok {
		return x.Uint64
	}
	return nil
}

func (m *FieldDft) GetSint32() *SInt32Dft {
	if x, ok := m.GetDft().(*FieldDft_Sint32); ok {
		return x.Sint32
	}
	return nil
}

func (m *FieldDft) GetSint64() *SInt64Dft {
	if x, ok := m.GetDft().(*FieldDft_Sint64); ok {
		return x.Sint64
	}
	return nil
}

func (m *FieldDft) GetFixed32() *Fixed32Dft {
	if x, ok := m.GetDft().(*FieldDft_Fixed32); ok {
		return x.Fixed32
	}
	return nil
}

func (m *FieldDft) GetFixed64() *Fixed64Dft {
	if x, ok := m.GetDft().(*FieldDft_Fixed64); ok {
		return x.Fixed64
	}
	return nil
}

func (m *FieldDft) GetSfixed32() *SFixed32Dft {
	if x, ok := m.GetDft().(*FieldDft_Sfixed32); ok {
		return x.Sfixed32
	}
	return nil
}

func (m *FieldDft) GetSfixed64() *SFixed64Dft {
	if x, ok := m.GetDft().(*FieldDft_Sfixed64); ok {
		return x.Sfixed64
	}
	return nil
}

func (m *FieldDft) GetBool() *BoolDft {
	if x, ok := m.GetDft().(*FieldDft_Bool); ok {
		return x.Bool
	}
	return nil
}

func (m *FieldDft) GetString_() *StringDft {
	if x, ok := m.GetDft().(*FieldDft_String_); ok {
		return x.String_
	}
	return nil
}

func (m *FieldDft) GetBytes() *BytesDft {
	if x, ok := m.GetDft().(*FieldDft_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (m *FieldDft) GetEnum() *EnumDft {
	if x, ok := m.GetDft().(*FieldDft_Enum); ok {
		return x.Enum
	}
	return nil
}

func (m *FieldDft) GetDuration() *DurationDft {
	if x, ok := m.GetDft().(*FieldDft_Duration); ok {
		return x.Duration
	}
	return nil
}

func (m *FieldDft) GetTimestamp() *TimestampDft {
	if x, ok := m.GetDft().(*FieldDft_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FieldDft) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FieldDft_Float)(nil),
		(*FieldDft_Double)(nil),
		(*FieldDft_Int32)(nil),
		(*FieldDft_Int64)(nil),
		(*FieldDft_Uint32)(nil),
		(*FieldDft_Uint64)(nil),
		(*FieldDft_Sint32)(nil),
		(*FieldDft_Sint64)(nil),
		(*FieldDft_Fixed32)(nil),
		(*FieldDft_Fixed64)(nil),
		(*FieldDft_Sfixed32)(nil),
		(*FieldDft_Sfixed64)(nil),
		(*FieldDft_Bool)(nil),
		(*FieldDft_String_)(nil),
		(*FieldDft_Bytes)(nil),
		(*FieldDft_Enum)(nil),
		(*FieldDft_Duration)(nil),
		(*FieldDft_Timestamp)(nil),
	}
}

type FloatDft struct {
	Dft                  float32  `protobuf:"fixed32,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FloatDft) Reset()         { *m = FloatDft{} }
func (m *FloatDft) String() string { return proto.CompactTextString(m) }
func (*FloatDft) ProtoMessage()    {}
func (*FloatDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{1}
}

func (m *FloatDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatDft.Unmarshal(m, b)
}
func (m *FloatDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatDft.Marshal(b, m, deterministic)
}
func (m *FloatDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatDft.Merge(m, src)
}
func (m *FloatDft) XXX_Size() int {
	return xxx_messageInfo_FloatDft.Size(m)
}
func (m *FloatDft) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatDft.DiscardUnknown(m)
}

var xxx_messageInfo_FloatDft proto.InternalMessageInfo

func (m *FloatDft) GetDft() float32 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type DoubleDft struct {
	Dft                  float64  `protobuf:"fixed64,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleDft) Reset()         { *m = DoubleDft{} }
func (m *DoubleDft) String() string { return proto.CompactTextString(m) }
func (*DoubleDft) ProtoMessage()    {}
func (*DoubleDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{2}
}

func (m *DoubleDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleDft.Unmarshal(m, b)
}
func (m *DoubleDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleDft.Marshal(b, m, deterministic)
}
func (m *DoubleDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleDft.Merge(m, src)
}
func (m *DoubleDft) XXX_Size() int {
	return xxx_messageInfo_DoubleDft.Size(m)
}
func (m *DoubleDft) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleDft.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleDft proto.InternalMessageInfo

func (m *DoubleDft) GetDft() float64 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type Int32Dft struct {
	Dft                  int32    `protobuf:"varint,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Dft) Reset()         { *m = Int32Dft{} }
func (m *Int32Dft) String() string { return proto.CompactTextString(m) }
func (*Int32Dft) ProtoMessage()    {}
func (*Int32Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{3}
}

func (m *Int32Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Dft.Unmarshal(m, b)
}
func (m *Int32Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Dft.Marshal(b, m, deterministic)
}
func (m *Int32Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Dft.Merge(m, src)
}
func (m *Int32Dft) XXX_Size() int {
	return xxx_messageInfo_Int32Dft.Size(m)
}
func (m *Int32Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Dft.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Dft proto.InternalMessageInfo

func (m *Int32Dft) GetDft() int32 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type Int64Dft struct {
	Dft                  int64    `protobuf:"varint,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Dft) Reset()         { *m = Int64Dft{} }
func (m *Int64Dft) String() string { return proto.CompactTextString(m) }
func (*Int64Dft) ProtoMessage()    {}
func (*Int64Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{4}
}

func (m *Int64Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Dft.Unmarshal(m, b)
}
func (m *Int64Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Dft.Marshal(b, m, deterministic)
}
func (m *Int64Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Dft.Merge(m, src)
}
func (m *Int64Dft) XXX_Size() int {
	return xxx_messageInfo_Int64Dft.Size(m)
}
func (m *Int64Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Dft.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Dft proto.InternalMessageInfo

func (m *Int64Dft) GetDft() int64 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type UInt32Dft struct {
	Dft                  uint32   `protobuf:"varint,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UInt32Dft) Reset()         { *m = UInt32Dft{} }
func (m *UInt32Dft) String() string { return proto.CompactTextString(m) }
func (*UInt32Dft) ProtoMessage()    {}
func (*UInt32Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{5}
}

func (m *UInt32Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt32Dft.Unmarshal(m, b)
}
func (m *UInt32Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt32Dft.Marshal(b, m, deterministic)
}
func (m *UInt32Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt32Dft.Merge(m, src)
}
func (m *UInt32Dft) XXX_Size() int {
	return xxx_messageInfo_UInt32Dft.Size(m)
}
func (m *UInt32Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt32Dft.DiscardUnknown(m)
}

var xxx_messageInfo_UInt32Dft proto.InternalMessageInfo

func (m *UInt32Dft) GetDft() uint32 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type UInt64Dft struct {
	Dft                  uint64   `protobuf:"varint,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UInt64Dft) Reset()         { *m = UInt64Dft{} }
func (m *UInt64Dft) String() string { return proto.CompactTextString(m) }
func (*UInt64Dft) ProtoMessage()    {}
func (*UInt64Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{6}
}

func (m *UInt64Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt64Dft.Unmarshal(m, b)
}
func (m *UInt64Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt64Dft.Marshal(b, m, deterministic)
}
func (m *UInt64Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt64Dft.Merge(m, src)
}
func (m *UInt64Dft) XXX_Size() int {
	return xxx_messageInfo_UInt64Dft.Size(m)
}
func (m *UInt64Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt64Dft.DiscardUnknown(m)
}

var xxx_messageInfo_UInt64Dft proto.InternalMessageInfo

func (m *UInt64Dft) GetDft() uint64 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type SInt32Dft struct {
	Dft                  int32    `protobuf:"zigzag32,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SInt32Dft) Reset()         { *m = SInt32Dft{} }
func (m *SInt32Dft) String() string { return proto.CompactTextString(m) }
func (*SInt32Dft) ProtoMessage()    {}
func (*SInt32Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{7}
}

func (m *SInt32Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SInt32Dft.Unmarshal(m, b)
}
func (m *SInt32Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SInt32Dft.Marshal(b, m, deterministic)
}
func (m *SInt32Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SInt32Dft.Merge(m, src)
}
func (m *SInt32Dft) XXX_Size() int {
	return xxx_messageInfo_SInt32Dft.Size(m)
}
func (m *SInt32Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_SInt32Dft.DiscardUnknown(m)
}

var xxx_messageInfo_SInt32Dft proto.InternalMessageInfo

func (m *SInt32Dft) GetDft() int32 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type SInt64Dft struct {
	Dft                  int64    `protobuf:"zigzag64,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SInt64Dft) Reset()         { *m = SInt64Dft{} }
func (m *SInt64Dft) String() string { return proto.CompactTextString(m) }
func (*SInt64Dft) ProtoMessage()    {}
func (*SInt64Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{8}
}

func (m *SInt64Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SInt64Dft.Unmarshal(m, b)
}
func (m *SInt64Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SInt64Dft.Marshal(b, m, deterministic)
}
func (m *SInt64Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SInt64Dft.Merge(m, src)
}
func (m *SInt64Dft) XXX_Size() int {
	return xxx_messageInfo_SInt64Dft.Size(m)
}
func (m *SInt64Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_SInt64Dft.DiscardUnknown(m)
}

var xxx_messageInfo_SInt64Dft proto.InternalMessageInfo

func (m *SInt64Dft) GetDft() int64 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type Fixed32Dft struct {
	Dft                  uint32   `protobuf:"fixed32,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fixed32Dft) Reset()         { *m = Fixed32Dft{} }
func (m *Fixed32Dft) String() string { return proto.CompactTextString(m) }
func (*Fixed32Dft) ProtoMessage()    {}
func (*Fixed32Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{9}
}

func (m *Fixed32Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fixed32Dft.Unmarshal(m, b)
}
func (m *Fixed32Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fixed32Dft.Marshal(b, m, deterministic)
}
func (m *Fixed32Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixed32Dft.Merge(m, src)
}
func (m *Fixed32Dft) XXX_Size() int {
	return xxx_messageInfo_Fixed32Dft.Size(m)
}
func (m *Fixed32Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixed32Dft.DiscardUnknown(m)
}

var xxx_messageInfo_Fixed32Dft proto.InternalMessageInfo

func (m *Fixed32Dft) GetDft() uint32 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type Fixed64Dft struct {
	Dft                  uint64   `protobuf:"fixed64,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fixed64Dft) Reset()         { *m = Fixed64Dft{} }
func (m *Fixed64Dft) String() string { return proto.CompactTextString(m) }
func (*Fixed64Dft) ProtoMessage()    {}
func (*Fixed64Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{10}
}

func (m *Fixed64Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fixed64Dft.Unmarshal(m, b)
}
func (m *Fixed64Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fixed64Dft.Marshal(b, m, deterministic)
}
func (m *Fixed64Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixed64Dft.Merge(m, src)
}
func (m *Fixed64Dft) XXX_Size() int {
	return xxx_messageInfo_Fixed64Dft.Size(m)
}
func (m *Fixed64Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixed64Dft.DiscardUnknown(m)
}

var xxx_messageInfo_Fixed64Dft proto.InternalMessageInfo

func (m *Fixed64Dft) GetDft() uint64 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type SFixed32Dft struct {
	Dft                  int32    `protobuf:"fixed32,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SFixed32Dft) Reset()         { *m = SFixed32Dft{} }
func (m *SFixed32Dft) String() string { return proto.CompactTextString(m) }
func (*SFixed32Dft) ProtoMessage()    {}
func (*SFixed32Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{11}
}

func (m *SFixed32Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SFixed32Dft.Unmarshal(m, b)
}
func (m *SFixed32Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SFixed32Dft.Marshal(b, m, deterministic)
}
func (m *SFixed32Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SFixed32Dft.Merge(m, src)
}
func (m *SFixed32Dft) XXX_Size() int {
	return xxx_messageInfo_SFixed32Dft.Size(m)
}
func (m *SFixed32Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_SFixed32Dft.DiscardUnknown(m)
}

var xxx_messageInfo_SFixed32Dft proto.InternalMessageInfo

func (m *SFixed32Dft) GetDft() int32 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type SFixed64Dft struct {
	Dft                  int64    `protobuf:"fixed64,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SFixed64Dft) Reset()         { *m = SFixed64Dft{} }
func (m *SFixed64Dft) String() string { return proto.CompactTextString(m) }
func (*SFixed64Dft) ProtoMessage()    {}
func (*SFixed64Dft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{12}
}

func (m *SFixed64Dft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SFixed64Dft.Unmarshal(m, b)
}
func (m *SFixed64Dft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SFixed64Dft.Marshal(b, m, deterministic)
}
func (m *SFixed64Dft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SFixed64Dft.Merge(m, src)
}
func (m *SFixed64Dft) XXX_Size() int {
	return xxx_messageInfo_SFixed64Dft.Size(m)
}
func (m *SFixed64Dft) XXX_DiscardUnknown() {
	xxx_messageInfo_SFixed64Dft.DiscardUnknown(m)
}

var xxx_messageInfo_SFixed64Dft proto.InternalMessageInfo

func (m *SFixed64Dft) GetDft() int64 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type BoolDft struct {
	Dft                  bool     `protobuf:"varint,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolDft) Reset()         { *m = BoolDft{} }
func (m *BoolDft) String() string { return proto.CompactTextString(m) }
func (*BoolDft) ProtoMessage()    {}
func (*BoolDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{13}
}

func (m *BoolDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolDft.Unmarshal(m, b)
}
func (m *BoolDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolDft.Marshal(b, m, deterministic)
}
func (m *BoolDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolDft.Merge(m, src)
}
func (m *BoolDft) XXX_Size() int {
	return xxx_messageInfo_BoolDft.Size(m)
}
func (m *BoolDft) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolDft.DiscardUnknown(m)
}

var xxx_messageInfo_BoolDft proto.InternalMessageInfo

func (m *BoolDft) GetDft() bool {
	if m != nil {
		return m.Dft
	}
	return false
}

type StringDft struct {
	Dft                  string   `protobuf:"bytes,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringDft) Reset()         { *m = StringDft{} }
func (m *StringDft) String() string { return proto.CompactTextString(m) }
func (*StringDft) ProtoMessage()    {}
func (*StringDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{14}
}

func (m *StringDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringDft.Unmarshal(m, b)
}
func (m *StringDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringDft.Marshal(b, m, deterministic)
}
func (m *StringDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringDft.Merge(m, src)
}
func (m *StringDft) XXX_Size() int {
	return xxx_messageInfo_StringDft.Size(m)
}
func (m *StringDft) XXX_DiscardUnknown() {
	xxx_messageInfo_StringDft.DiscardUnknown(m)
}

var xxx_messageInfo_StringDft proto.InternalMessageInfo

func (m *StringDft) GetDft() string {
	if m != nil {
		return m.Dft
	}
	return ""
}

type BytesDft struct {
	Dft                  []byte   `protobuf:"bytes,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesDft) Reset()         { *m = BytesDft{} }
func (m *BytesDft) String() string { return proto.CompactTextString(m) }
func (*BytesDft) ProtoMessage()    {}
func (*BytesDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{15}
}

func (m *BytesDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesDft.Unmarshal(m, b)
}
func (m *BytesDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesDft.Marshal(b, m, deterministic)
}
func (m *BytesDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesDft.Merge(m, src)
}
func (m *BytesDft) XXX_Size() int {
	return xxx_messageInfo_BytesDft.Size(m)
}
func (m *BytesDft) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesDft.DiscardUnknown(m)
}

var xxx_messageInfo_BytesDft proto.InternalMessageInfo

func (m *BytesDft) GetDft() []byte {
	if m != nil {
		return m.Dft
	}
	return nil
}

type EnumDft struct {
	Dft                  int32    `protobuf:"varint,1,opt,name=dft,proto3" json:"dft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumDft) Reset()         { *m = EnumDft{} }
func (m *EnumDft) String() string { return proto.CompactTextString(m) }
func (*EnumDft) ProtoMessage()    {}
func (*EnumDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{16}
}

func (m *EnumDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumDft.Unmarshal(m, b)
}
func (m *EnumDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumDft.Marshal(b, m, deterministic)
}
func (m *EnumDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumDft.Merge(m, src)
}
func (m *EnumDft) XXX_Size() int {
	return xxx_messageInfo_EnumDft.Size(m)
}
func (m *EnumDft) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumDft.DiscardUnknown(m)
}

var xxx_messageInfo_EnumDft proto.InternalMessageInfo

func (m *EnumDft) GetDft() int32 {
	if m != nil {
		return m.Dft
	}
	return 0
}

type DurationDft struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DurationDft) Reset()         { *m = DurationDft{} }
func (m *DurationDft) String() string { return proto.CompactTextString(m) }
func (*DurationDft) ProtoMessage()    {}
func (*DurationDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{17}
}

func (m *DurationDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DurationDft.Unmarshal(m, b)
}
func (m *DurationDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DurationDft.Marshal(b, m, deterministic)
}
func (m *DurationDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DurationDft.Merge(m, src)
}
func (m *DurationDft) XXX_Size() int {
	return xxx_messageInfo_DurationDft.Size(m)
}
func (m *DurationDft) XXX_DiscardUnknown() {
	xxx_messageInfo_DurationDft.DiscardUnknown(m)
}

var xxx_messageInfo_DurationDft proto.InternalMessageInfo

type TimestampDft struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimestampDft) Reset()         { *m = TimestampDft{} }
func (m *TimestampDft) String() string { return proto.CompactTextString(m) }
func (*TimestampDft) ProtoMessage()    {}
func (*TimestampDft) Descriptor() ([]byte, []int) {
	return fileDescriptor_71063672d45bc740, []int{18}
}

func (m *TimestampDft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimestampDft.Unmarshal(m, b)
}
func (m *TimestampDft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimestampDft.Marshal(b, m, deterministic)
}
func (m *TimestampDft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimestampDft.Merge(m, src)
}
func (m *TimestampDft) XXX_Size() int {
	return xxx_messageInfo_TimestampDft.Size(m)
}
func (m *TimestampDft) XXX_DiscardUnknown() {
	xxx_messageInfo_TimestampDft.DiscardUnknown(m)
}

var xxx_messageInfo_TimestampDft proto.InternalMessageInfo

var E_Dft = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*FieldDft)(nil),
	Field:         1081,
	Name:          "dft.dft",
	Tag:           "bytes,1081,opt,name=dft",
	Filename:      "dft/dft.proto",
}

func init() {
	proto.RegisterType((*FieldDft)(nil), "dft.FieldDft")
	proto.RegisterType((*FloatDft)(nil), "dft.FloatDft")
	proto.RegisterType((*DoubleDft)(nil), "dft.DoubleDft")
	proto.RegisterType((*Int32Dft)(nil), "dft.Int32Dft")
	proto.RegisterType((*Int64Dft)(nil), "dft.Int64Dft")
	proto.RegisterType((*UInt32Dft)(nil), "dft.UInt32Dft")
	proto.RegisterType((*UInt64Dft)(nil), "dft.UInt64Dft")
	proto.RegisterType((*SInt32Dft)(nil), "dft.SInt32Dft")
	proto.RegisterType((*SInt64Dft)(nil), "dft.SInt64Dft")
	proto.RegisterType((*Fixed32Dft)(nil), "dft.Fixed32Dft")
	proto.RegisterType((*Fixed64Dft)(nil), "dft.Fixed64Dft")
	proto.RegisterType((*SFixed32Dft)(nil), "dft.SFixed32Dft")
	proto.RegisterType((*SFixed64Dft)(nil), "dft.SFixed64Dft")
	proto.RegisterType((*BoolDft)(nil), "dft.BoolDft")
	proto.RegisterType((*StringDft)(nil), "dft.StringDft")
	proto.RegisterType((*BytesDft)(nil), "dft.BytesDft")
	proto.RegisterType((*EnumDft)(nil), "dft.EnumDft")
	proto.RegisterType((*DurationDft)(nil), "dft.DurationDft")
	proto.RegisterType((*TimestampDft)(nil), "dft.TimestampDft")
	proto.RegisterExtension(E_Dft)
}

func init() { proto.RegisterFile("dft/dft.proto", fileDescriptor_71063672d45bc740) }

var fileDescriptor_71063672d45bc740 = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xcb, 0x8e, 0xd3, 0x4a,
	0x10, 0x86, 0x4f, 0x26, 0x37, 0xa7, 0x73, 0x9d, 0x96, 0x0e, 0x6a, 0x01, 0x03, 0xa3, 0x08, 0xd0,
	0x48, 0x68, 0x1c, 0x48, 0x2c, 0x2f, 0x58, 0x46, 0x61, 0x04, 0x2b, 0xa4, 0x84, 0xd9, 0xb0, 0x8b,
	0xe3, 0x0b, 0x46, 0x8e, 0x3b, 0x8a, 0xdb, 0x12, 0xbc, 0x01, 0x2b, 0xde, 0x87, 0xb7, 0x43, 0x5d,
	0x7d, 0x49, 0x39, 0xce, 0x32, 0xf5, 0x7d, 0xf5, 0x77, 0xdc, 0x2e, 0x17, 0x19, 0x86, 0xb1, 0x98,
	0x85, 0xb1, 0x70, 0x0f, 0x47, 0x2e, 0x38, 0x6d, 0x86, 0xb1, 0x78, 0x7a, 0x9b, 0x70, 0x9e, 0x64,
	0xd1, 0x0c, 0x4a, 0x41, 0x19, 0xcf, 0xc2, 0xa8, 0xd8, 0x1d, 0xd3, 0x83, 0xe0, 0x47, 0xa5, 0x4d,
	0xff, 0x74, 0x88, 0xf3, 0x90, 0x46, 0x59, 0xb8, 0x8a, 0x05, 0x7d, 0x4d, 0xda, 0x71, 0xc6, 0xb7,
	0x82, 0x35, 0x6e, 0x1b, 0x77, 0xfd, 0xf9, 0xd0, 0x95, 0x71, 0x0f, 0xb2, 0xb2, 0x8a, 0xc5, 0xa7,
	0xff, 0xd6, 0x8a, 0xd2, 0x3b, 0xd2, 0x09, 0x79, 0x19, 0x64, 0x11, 0xbb, 0x02, 0x6f, 0x04, 0xde,
	0x0a, 0x4a, 0x4a, 0xd4, 0x5c, 0x06, 0xa6, 0xb9, 0x58, 0xcc, 0x59, 0x13, 0x05, 0x7e, 0x96, 0x15,
	0x1d, 0x08, 0x54, 0x6b, 0xbe, 0xc7, 0x5a, 0x55, 0xcd, 0xf7, 0x4e, 0x9a, 0xef, 0xc9, 0x73, 0x4b,
	0x15, 0xd7, 0x46, 0xe7, 0x3e, 0xa2, 0x3c, 0xcd, 0x8d, 0xe9, 0x7b, 0xac, 0x73, 0x66, 0x9a, 0x48,
	0xcd, 0xa5, 0x59, 0xa8, 0xcc, 0x2e, 0x32, 0x37, 0x38, 0xb3, 0xb0, 0x99, 0x85, 0xca, 0x74, 0xce,
	0x4c, 0x9b, 0xa9, 0x38, 0x7d, 0x4b, 0xba, 0x71, 0xfa, 0x33, 0x0a, 0x17, 0x73, 0xd6, 0x03, 0x75,
	0xac, 0x2e, 0x52, 0xd5, 0x94, 0x6b, 0x0c, 0x2b, 0xfb, 0x1e, 0x23, 0xe7, 0xb2, 0x09, 0x36, 0x06,
	0x75, 0x89, 0x53, 0x98, 0xe8, 0x3e, 0xd8, 0x13, 0xf5, 0x2f, 0x2a, 0xd9, 0xd6, 0x39, 0xf9, 0xbe,
	0xc7, 0x06, 0x35, 0xdf, 0xc4, 0x5b, 0x87, 0x4e, 0x49, 0x2b, 0xe0, 0x3c, 0x63, 0x43, 0x70, 0x07,
	0xe0, 0x2e, 0x39, 0xcf, 0x94, 0x07, 0x0c, 0xee, 0x41, 0x1c, 0xd3, 0x3c, 0x61, 0x23, 0x7c, 0x0f,
	0x50, 0x32, 0xf7, 0x00, 0x3f, 0xe4, 0x6b, 0x0d, 0x7e, 0x89, 0xa8, 0x60, 0x63, 0xf4, 0x5a, 0x97,
	0xb2, 0xa2, 0x5f, 0x2b, 0x50, 0x79, 0x68, 0x94, 0x97, 0x7b, 0x36, 0x41, 0x87, 0x7e, 0xcc, 0xcb,
	0xbd, 0x3e, 0x54, 0x32, 0xf9, 0x20, 0x61, 0x79, 0xdc, 0x8a, 0x94, 0xe7, 0xec, 0x7f, 0xf4, 0x20,
	0x2b, 0x5d, 0xd4, 0x0f, 0x62, 0x1c, 0xfa, 0x9e, 0xf4, 0x44, 0xba, 0x8f, 0x0a, 0xb1, 0xdd, 0x1f,
	0xd8, 0x13, 0x68, 0xb8, 0x86, 0x86, 0xaf, 0xa6, 0xaa, 0x3a, 0x4e, 0xd6, 0xb2, 0x4d, 0xe4, 0x27,
	0x33, 0x7d, 0x4e, 0x1c, 0x33, 0xf1, 0x74, 0x02, 0x25, 0xf8, 0x1a, 0xae, 0xd6, 0x40, 0x6f, 0x48,
	0xcf, 0xce, 0x39, 0xc6, 0x8d, 0xb5, 0x69, 0x36, 0x93, 0x83, 0x69, 0x1b, 0x53, 0xb8, 0x75, 0x4c,
	0x9b, 0x36, 0xfa, 0xf1, 0x52, 0xf3, 0xb0, 0x82, 0x6b, 0xdd, 0x2d, 0x8b, 0x37, 0x97, 0xba, 0xaf,
	0x2b, 0xb8, 0xd6, 0x4d, 0x15, 0x7e, 0x41, 0xc8, 0x69, 0x82, 0x30, 0xef, 0x56, 0x79, 0xad, 0xbf,
	0xa3, 0xf8, 0x4b, 0xd2, 0xdf, 0x5c, 0x0e, 0x18, 0x9f, 0x09, 0xb5, 0x84, 0x89, 0x12, 0x9e, 0x91,
	0xae, 0x1e, 0x34, 0x0c, 0x9d, 0xd3, 0xbf, 0x37, 0xf3, 0x85, 0x71, 0xcf, 0xde, 0xab, 0x99, 0x2a,
	0x4c, 0x07, 0x36, 0x59, 0x4f, 0xd3, 0x85, 0x57, 0x32, 0x24, 0x7d, 0x34, 0x42, 0xd3, 0x11, 0x19,
	0xe0, 0x01, 0xf9, 0xb0, 0x84, 0x06, 0x7a, 0xe3, 0xaa, 0x3d, 0xea, 0x9a, 0x3d, 0xea, 0xc2, 0xca,
	0xfc, 0x72, 0x90, 0x7d, 0x05, 0xfb, 0xeb, 0xe0, 0x75, 0xa9, 0x97, 0x29, 0xe4, 0xff, 0x6e, 0x34,
	0x96, 0x6f, 0xbe, 0xbd, 0x4a, 0x52, 0xf1, 0xbd, 0x0c, 0xdc, 0x1d, 0xdf, 0xcf, 0x7e, 0xcc, 0x93,
	0xe4, 0x5d, 0xa1, 0x16, 0xf2, 0xee, 0x3e, 0x89, 0xf2, 0x7b, 0xbd, 0xb6, 0x83, 0x0e, 0xd4, 0x16,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x28, 0x7b, 0x50, 0x89, 0xc8, 0x05, 0x00, 0x00,
}
